version: "3"
services:  
  redis:
    command: [ "redis-server", "/redis.conf" ]
    image: "redis:latest"
    ports:
        - "6379:6379"
    volumes:
      - ./config/redis.conf:/redis.conf

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:    
    env_file:
      - ".env"      
    build: . 
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis    
      - db
    volumes:
      - .:/app
  migration:
    
    command: python manage.py migrate --noinput
    volumes:
      - .:/app
    depends_on:
      - db
      
  celery:
    container_name: flight-blender-worker
    build:
      context: "."    
    
    env_file:
      - ".env"
    command: celery --app=flight_blender worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

      
  beat:
    container_name: flight-blender-beat
    build:
      context: "."    
      
    env_file:
      - ".env"
    hostname: beat    
    command: celery --app=flight_blender beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  