version: "3"
services:  
  redis:
    command: [ "redis-server", "/redis.conf" ]
    image: "redis:latest"
    ports:
        - "6379:6379"
    volumes:
      - ./config/redis.conf:/redis.conf

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
        
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ".env"

  web:    
    env_file:
      - ".env"      
    build: . 
    image: openskies-sh/flight-blender
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis    
      - db
    volumes:
      - .:/app
  migration:
    
    command: python manage.py migrate --noinput
    image: openskies-sh/flight-blender
    volumes:
      - .:/app
    depends_on:
      - db
      
  celery:
    container_name: flight-blender-worker
    image: openskies-sh/flight-blender
    build:
      context: "."    
    
    env_file:
      - ".env"
    command: celery --app=flight_blender worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

      
  beat:
    container_name: flight-blender-beat
    image: openskies-sh/flight-blender
    build:
      context: "."    
      
    env_file:
      - ".env"
    hostname: beat    
    command: celery --app=flight_blender beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  
volumes:
  app:
  db_data:
  