version: "3"
services:  
  redis:
    command: [ "redis-server", "/redis.conf" ]
    image: "redis:latest"
    ports:
        - "6379:6379"
    volumes:
      - ./config/redis.conf:/redis.conf


  web:    
    env_file:
      - ".env"      
    image: openskiessh/flight-blender
    depends_on:
      - redis
      
    volumes:
      - .:/app

  celery:
    container_name: flight-blender-worker
    build:
      context: "."    
    
    command: celery worker --app=flight_blender --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

      
  beat:
    container_name: flight-blender-beat
    build:
      context: "."    
      
    env_file:
      - ".env"
    hostname: beat    
    command: celery --app=flight_blender beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  