[tool.black]
line-length = 150
target-version = ['py310']
exclude = '''
/(
  | migrations
)/

'''

[tool.isort]
profile = "black"
skip = "migrations"

[tool.ruff]
line-length = 150
target-version = "py310"
exclude = ["migrations"]

# [tool.ruff.lint]
# # 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
# select = ["E4", "E7", "E9", "F", "B"]